### ISSUE TITLE
Change Color Theme

### ISSUE THREAD

**Issue by Tejas242** [Tejas242/Music-Player-Web#2]
Allow users to switch between different color themes for the user interface. Provide at least three theme options, and ensure a smooth transition between them.

**Difficulty:** Beginner

**Comment by Ahnaf-codes** [comment]
@Tejas242 i can do this please assign me

**Comment by KartikLabhshetwar** [comment]
I can do it pls assign it to me

**Comment by AparajitaSingh121416** [comment]
Hey @Tejas242 , please assign this issue to me, i can resolve this issue to my level-best.

**Comment by aarth01** [comment]
hey @Tejas242 can you assign this issue to me
