### ISSUE TITLE
Bug Fix - Song Progress Bar

### ISSUE THREAD

**Issue by Tejas242** [Tejas242/Music-Player-Web#5]
Fix a bug where the song progress bar occasionally displays incorrect progress. Investigate and resolve this issue.

**Difficulty:** Beginner

**Comment by sachinspeaks** [comment]
Hey Tejas I want to work on this issue, can you please assign it to me?

**Comment by AparajitaSingh121416** [comment]
hey @Tejas242 , i know i can resolve this bug. Please assign this issue to me.

**Comment by sachinspeaks** [comment]
Hello @Tejas242 I saw the progress bar but I am not able to find the bug. Can you please tell me when exactly is the bar showing incorrect progress?

**Comment by Tejas242** [comment]
Sorry I haven't stated it clearly in description

![Screenshot_20231005_123045.jpg](https://github.com/Tejas242/Music-Player-Web/assets/59790915/ce3395cd-9b0c-426a-b856-95c886d80993)

As you can see when in screenshot it show NaN in the song length before playing the song whenever we open the player.
