### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by Tejas242** [Tejas242/Music-Player-Web#9]
Optimize the CSS for mobile devices, ensuring that the music player works well on smaller screens.

**Difficulty:** Beginner

**Comment by KartikLabhshetwar** [comment]
hey @Tejas242 can you pls assign this issue to me ?

**Comment by AparajitaSingh121416** [comment]
hey @Tejas242 please assign this issue to me. i will be highly grateful. i will give it my all

**Comment by RacHiT101** [comment]
It works good on small screens

![image](https://github.com/Tejas242/Music-Player-Web/assets/102236245/28ff7eae-d743-494c-94e4-f84161cbdb7c)
